openapi: 3.0.0
info:
  title: Login Authentication API
  version: "1.0.0"
  description: This API is used for user login authentication.
servers:
  - url: http://localhost:5000/api
paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate a user with email and password.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: admin1@gmail.com
                password:
                  type: string
                  example: test123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: ""
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: "12345"
                          fullName:
                            type: string
                            example: "Admin User"
                          email:
                            type: string
                            example: "admin1@gmail.com"
                          role:
                            type: string
                            example: "admin"
                          phone:
                            type: string
                            example: "+9779800000000"
                      accessToken:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR..."
        "400":
          description: Bad request - missing or invalid fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Email and password are required."
                  data:
                    type: object
                    example: {}
        "401":
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid email or password."
                  data:
                    type: object
                    example: {}
